INSERT INTO CertificationBody(CerID,ProductName,CertificationNumber,CertificationCriteria,CompanyContactInfo,CertificationCompany)
VALUES('1001','Banana','2362024','Not Using Genetically Modified Organism(GMO)','+1 236 348 8524','USDA Organic')
INSERT INTO CertificationBody(CerID,ProductName,CertificationNumber,CertificationCriteria,CompanyContactInfo,CertificationCompany)
VALUES('1002','Banana','2362024','Not Using Genetically Modified Organism(GMO)','+1 312 236 4546','Non-GMO')
INSERT INTO CertificationBody(CerID,ProductName,CertificationNumber,CertificationCriteria,CompanyContactInfo,CertificationCompany)
VALUES('1003','Apricot','2362025','Not Using Genetically Modified Organism(GMO)','+1 236 348 8524','USDA Organic')
INSERT INTO CertificationBody(CerID,ProductName,CertificationNumber,CertificationCriteria,CompanyContactInfo,CertificationCompany)
VALUES('1004','Apricot','2362025','Not Using Genetically Modified Organism(GMO)','+1 312 236 4546','Non-GMO')
INSERT INTO CertificationBody(CerID,ProductName,CertificationNumber,CertificationCriteria,CompanyContactInfo,CertificationCompany)
VALUES('1005','Cherry','2362026','Not Using Genetically Modified Organism(GMO)','+1 236 348 8524','USDA Organic')
INSERT INTO CertificationBody(CerID,ProductName,CertificationNumber,CertificationCriteria,CompanyContactInfo,CertificationCompany)
VALUES('1006','Cherry','2362026','Not Using Genetically Modified Organism(GMO)','+1 312 236 4546','Non-GMO')
INSERT INTO CertificationBody(CerID,ProductName,CertificationNumber,CertificationCriteria,CompanyContactInfo,CertificationCompany)
VALUES('1007','Blackberry','2362027','Not Using Genetically Modified Organism(GMO)','+1 236 348 8524','USDA Organic')
INSERT INTO CertificationBody(CerID,ProductName,CertificationNumber,CertificationCriteria,CompanyContactInfo,CertificationCompany)
VALUES('1008','Blackberry','2362027','Not Using Genetically Modified Organism(GMO)','+1 312 236 4546','Non-GMO')
INSERT INTO CertificationBody(CerID,ProductName,CertificationNumber,CertificationCriteria,CompanyContactInfo,CertificationCompany)
VALUES('1009','Pumpkin','2362028','Not Using Genetically Modified Organism(GMO)','+1 236 348 8524','USDA Organic')
INSERT INTO CertificationBody(CerID,ProductName,CertificationNumber,CertificationCriteria,CompanyContactInfo,CertificationCompany)
VALUES('1010','Pumpkin','2362028','Not Using Genetically Modified Organism(GMO)','+1 312 236 4546','Non-GMO')
INSERT INTO CertificationBody(CerID,ProductName,CertificationNumber,CertificationCriteria,CompanyContactInfo,CertificationCompany)
VALUES('1011','Eggplant','2362029','Not Using Genetically Modified Organism(GMO)','+1 236 348 8524','USDA Organic')
INSERT INTO CertificationBody(CerID,ProductName,CertificationNumber,CertificationCriteria,CompanyContactInfo,CertificationCompany)
VALUES('1012','Eggplant','2362029','Not Using Genetically Modified Organism(GMO)','+1 312 236 4546','Non-GMO')
INSERT INTO CertificationBody(CerID,ProductName,CertificationNumber,CertificationCriteria,CompanyContactInfo,CertificationCompany)
VALUES('1013','Mushroom','2362030','Not Using Genetically Modified Organism(GMO)','+1 236 348 8524','USDA Organic')
INSERT INTO CertificationBody(CerID,ProductName,CertificationNumber,CertificationCriteria,CompanyContactInfo,CertificationCompany)
VALUES('1014','Mushroom','2362030','Not Using Genetically Modified Organism(GMO)','+1 312 236 4546','Non-GMO')
INSERT INTO CertificationBody(CerID,ProductName,CertificationNumber,CertificationCriteria,CompanyContactInfo,CertificationCompany)
VALUES('1015','Tomato','2362031','Not Using Genetically Modified Organism(GMO)','+1 236 348 8524','USDA Organic')
INSERT INTO CertificationBody(CerID,ProductName,CertificationNumber,CertificationCriteria,CompanyContactInfo,CertificationCompany)
VALUES('1016','Tomato','2362031','Not Using Genetically Modified Organism(GMO)','+1 312 236 4546','Non-GMO')
INSERT INTO CertificationBody(CerID,ProductName,CertificationNumber,CertificationCriteria,CompanyContactInfo,CertificationCompany)
VALUES('1017','Butter','2362032','Made without ingredients derived from genetically modified organisms','+1 354 745 6114','AWA')
INSERT INTO CertificationBody(CerID,ProductName,CertificationNumber,CertificationCriteria,CompanyContactInfo,CertificationCompany)
VALUES('1018','Butter','2362032','Made without ingredients derived from genetically modified organisms','+1 312 236 4546','Non-GMO')
INSERT INTO CertificationBody(CerID,ProductName,CertificationNumber,CertificationCriteria,CompanyContactInfo,CertificationCompany)
VALUES('1019','Yoghurt','2362033','Made without ingredients derived from genetically modified organisms','+1 354 745 6114','AWA')
INSERT INTO CertificationBody(CerID,ProductName,CertificationNumber,CertificationCriteria,CompanyContactInfo,CertificationCompany)
VALUES('1020','Yoghurt','2362033','Made without ingredients derived from genetically modified organisms','+1 312 236 4546','Non-GMO')
INSERT INTO CertificationBody(CerID,ProductName,CertificationNumber,CertificationCriteria,CompanyContactInfo,CertificationCompany)
VALUES('1021','Cream','2362034','Made without ingredients derived from genetically modified organisms','+1 354 745 6114','AWA')
INSERT INTO CertificationBody(CerID,ProductName,CertificationNumber,CertificationCriteria,CompanyContactInfo,CertificationCompany)
VALUES('1022','Cream','2362034','Made without ingredients derived from genetically modified organisms','+1 312 236 4546','Non-GMO')
INSERT INTO CertificationBody(CerID,ProductName,CertificationNumber,CertificationCriteria,CompanyContactInfo,CertificationCompany)
VALUES('1023','Cheese','2362035','Made without ingredients derived from genetically modified organisms','+1 354 745 6114','AWA')
INSERT INTO CertificationBody(CerID,ProductName,CertificationNumber,CertificationCriteria,CompanyContactInfo,CertificationCompany)
VALUES('1024','Cheese','2362035','Made without ingredients derived from genetically modified organisms','+1 312 236 4546','Non-GMO')
SELECT*FROM CertificationBody
