INSERT INTO Contain(ProductID,IngID,Description)
VALUES('1','101','ProductItself')
INSERT INTO Contain(ProductID,IngID,Description)
VALUES('2','102','ProductItself')
INSERT INTO Contain(ProductID,IngID,Description)
VALUES('3','103','ProductItself')
INSERT INTO Contain(ProductID,IngID,Description)
VALUES('4','104','ProductItself')
INSERT INTO Contain(ProductID,IngID,Description)
VALUES('5','105','ProductItself')
INSERT INTO Contain(ProductID,IngID,Description)
VALUES('6','106','ProductItself')
INSERT INTO Contain(ProductID,IngID,Description)
VALUES('7','107','ProductItself')
INSERT INTO Contain(ProductID,IngID,Description)
VALUES('8','108','ProductItself')
INSERT INTO Contain(ProductID,IngID,Description)
VALUES('9','109','Milk')
INSERT INTO Contain(ProductID,IngID,Description)
VALUES('10','110','Milk')
INSERT INTO Contain(ProductID,IngID,Description)
VALUES('11','111','Milk')
INSERT INTO Contain(ProductID,IngID,Description)
VALUES('12','112','Milk')

SELECT*FROM Contain