INSERT INTO Ingredient(IngID,IngredientName,NutritionalInfo,IngredientSource)
VALUES('101','Product Itself','Potassium','Plant')
INSERT INTO Ingredient(IngID,IngredientName,NutritionalInfo,IngredientSource)
VALUES('102','Product Itself','B6','Plant')
INSERT INTO Ingredient(IngID,IngredientName,NutritionalInfo,IngredientSource)
VALUES('103','Product Itself','Vitamin C','Plant')
INSERT INTO Ingredient(IngID,IngredientName,NutritionalInfo,IngredientSource)
VALUES('104','Product Itself','Vitamin A','Plant')
INSERT INTO Ingredient(IngID,IngredientName,NutritionalInfo,IngredientSource)
VALUES('105','Product Itself','Beta-Carotene','Plant')
INSERT INTO Ingredient(IngID,IngredientName,NutritionalInfo,IngredientSource)
VALUES('106','Product Itself','Vitamin C','Plant')
INSERT INTO Ingredient(IngID,IngredientName,NutritionalInfo,IngredientSource)
VALUES('107','Product Itself','B6','Plant')
INSERT INTO Ingredient(IngID,IngredientName,NutritionalInfo,IngredientSource)
VALUES('108','Product Itself','Vitamin C','Plant')
INSERT INTO Ingredient(IngID,IngredientName,NutritionalInfo,IngredientSource)
VALUES('109','Product Itself','Vitamin E','Plant')
INSERT INTO Ingredient(IngID,IngredientName,NutritionalInfo,IngredientSource)
VALUES('110','Product Itself','Vitamin K','Plant')
INSERT INTO Ingredient(IngID,IngredientName,NutritionalInfo,IngredientSource)
VALUES('111','Product Itself','Vitamin A','Plant')
INSERT INTO Ingredient(IngID,IngredientName,NutritionalInfo,IngredientSource)
VALUES('112','Product Itself','Vitamin C','Plant')
INSERT INTO Ingredient(IngID,IngredientName,NutritionalInfo,IngredientSource)
VALUES('113','Product Itself','Folate','Plant')
INSERT INTO Ingredient(IngID,IngredientName,NutritionalInfo,IngredientSource)
VALUES('114','Product Itself','Vitamin A','Plant')
INSERT INTO Ingredient(IngID,IngredientName,NutritionalInfo,IngredientSource)
VALUES('115','Product Itself','Vitamin C','Plant')
INSERT INTO Ingredient(IngID,IngredientName,NutritionalInfo,IngredientSource)
VALUES('116','Product Itself','Vitamin C','Plant')
INSERT INTO Ingredient(IngID,IngredientName,NutritionalInfo,IngredientSource)
VALUES('117','Product Itself','Vitamin D','Plant')
INSERT INTO Ingredient(IngID,IngredientName,NutritionalInfo,IngredientSource)
VALUES('118','Product Itself','Vitamin E','Plant')
INSERT INTO Ingredient(IngID,IngredientName,NutritionalInfo,IngredientSource)
VALUES('119','Product Itself','B12','Plant')
INSERT INTO Ingredient(IngID,IngredientName,NutritionalInfo,IngredientSource)
VALUES('120','Product Itself','Vitamin C','Plant')
INSERT INTO Ingredient(IngID,IngredientName,NutritionalInfo,IngredientSource)
VALUES('121','Product Itself','Vitamin K','Plant')
INSERT INTO Ingredient(IngID,IngredientName,NutritionalInfo,IngredientSource)
VALUES('122','Product Itself','Potassium','Plant')
INSERT INTO Ingredient(IngID,IngredientName,NutritionalInfo,IngredientSource)
VALUES('123','Product Itself','Folate','Plant')
INSERT INTO Ingredient(IngID,IngredientName,NutritionalInfo,IngredientSource)
VALUES('124','Milk','Vitamin A','Animal')
INSERT INTO Ingredient(IngID,IngredientName,NutritionalInfo,IngredientSource)
VALUES('125','Milk','Vitamin D','Animal')
INSERT INTO Ingredient(IngID,IngredientName,NutritionalInfo,IngredientSource)
VALUES('126','Milk','Vitamin E','Animal')
INSERT INTO Ingredient(IngID,IngredientName,NutritionalInfo,IngredientSource)
VALUES('127','Milk','K12','Animal')
INSERT INTO Ingredient(IngID,IngredientName,NutritionalInfo,IngredientSource)
VALUES('128','Milk','Vitamin B','Animal')
INSERT INTO Ingredient(IngID,IngredientName,NutritionalInfo,IngredientSource)
VALUES('129','Milk','Calcium','Animal')
INSERT INTO Ingredient(IngID,IngredientName,NutritionalInfo,IngredientSource)
VALUES('130','Milk','B12','Animal')
INSERT INTO Ingredient(IngID,IngredientName,NutritionalInfo,IngredientSource)
VALUES('131','Milk','Vitamin A','Animal')
INSERT INTO Ingredient(IngID,IngredientName,NutritionalInfo,IngredientSource)
VALUES('132','Milk','Vitamin D','Animal')
INSERT INTO Ingredient(IngID,IngredientName,NutritionalInfo,IngredientSource)
VALUES('133','Milk','Vitamin E','Animal')
INSERT INTO Ingredient(IngID,IngredientName,NutritionalInfo,IngredientSource)
VALUES('134','Milk','Vitamin A','Animal')
INSERT INTO Ingredient(IngID,IngredientName,NutritionalInfo,IngredientSource)
VALUES('135','Milk','Vitamin D','Animal')
INSERT INTO Ingredient(IngID,IngredientName,NutritionalInfo,IngredientSource)
VALUES('136','Milk','Vitamin K','Animal')
INSERT INTO Ingredient(IngID,IngredientName,NutritionalInfo,IngredientSource)
VALUES('137','Milk','B12','Animal')

SELECT*FROM Ingredient
